# fly.toml app configuration file generated for tool-api on 2023-10-23T06:58:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tool-api"
primary_region = "ord"

[build]
image = "tools-backend"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
